Connector Specifications
UnifiedPush/UP-spec pull request #3
Opened 2020-12-21 14:23 UTC by sparchatus

2020-12-21 18:14 UTC, p1gp1g requested changes
Thanks :smile: . We need to add the registration part on the connector specification now.

2020-12-21 18:14 UTC, p1gp1g commented on connector.md
> +The exposed service MUST handle 2 different types of messages:
Did you forget TYPE_DITRIBUTOR_UNREGISTERED, or was it wanted?. The lib can work even if there isn't this type of message so I think it SHOULD handle this one

2020-12-21 18:14 UTC, p1gp1g commented on connector.md
> +The distributor sends this type of message to deliver a push message from the provider for the given client.
```
< The distributor sends this type of message to deliver a push message from the provider for the given client.
> The distributor sends this type of message to forward a push message received from the provider to the end user application.
```

2020-12-21 19:19 UTC, sparchatus commented on connector.md
> +The library itself does not declare anything in the manifest. The developer integrating the library should add the following lines to the manifest Wher {PushReceiverService} is the service implementi
Sounds good to me

2020-12-22 14:57 UTC, p1gp1g approved these changes

2020-12-22 14:57 UTC, merged